### ISSUE TITLE
Proxy maker issue

### ISSUE THREAD

**Issue by ZenithDoom** [Kingal1337/YugiohProxyMaker#4]
Exception in thread "main" java.lang.NullPointerException
        at yugiohproxymaker.CardCreator.drawCardType(CardCreator.java:444)
        at yugiohproxymaker.CardCreator.drawCard(CardCreator.java:215)
        at yugiohproxymaker.CardCreator.renderCard(CardCreator.java:112)
        at yugiohproxymaker.Main.generate(Main.java:240)
        at yugiohproxymaker.Main.main(Main.java:71)

**Comment by ZenithDoom** [comment]
version 1.2.0

**Comment by ZenithDoom** [comment]
#created by Player
#main
9056100
53921056
88494899
81275309
41090784
81825063
81825063
101104020
101104020
59546528
59546528
50032342
50032342
44877690
44877690
92065772
92065772
92065772
73061465
56704140
56704140
82498947
82498947
82498947
23950192
23950192
90311614
90311614
17197110
17197110
17197110
64990807
64990807
64990807
84206435
84206435
84206435
10691144
10691144
10691144
#extra
52687916
52687916
52687916
65749035
50321796
70583986
!side
23950192
90311614

**Comment by Kingal1337** [comment]
The issue has been fixed in release 1.3.0.
